# Generated by Django 3.1.2 on 2021-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('date', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
    ]
