# Generated by Django 3.1.2 on 2021-01-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210123_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='money',
            field=models.IntegerField(),
        ),
    ]
