# Generated by Django 3.1.2 on 2021-01-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210128_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
