# Generated by Django 3.1.2 on 2021-01-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210128_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='image',
        ),
    ]
