# Generated by Django 3.1.2 on 2021-01-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_bill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
