# Generated by Django 3.1.2 on 2021-01-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='src_image',
            field=models.CharField(max_length=1000),
        ),
    ]
