# Generated by Django 3.1.2 on 2021-01-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210128_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
